global: 
  train_path: "train_data.json"
  test_path: "test_data.json"
  valid_path: "val_data.json"

  image_folder: ""

  EPOCHS: 100
  BATCH_SIZE: 32
  checkpoint_path : "/kaggle/working/model_checkpoint/modelCLIP.pt"
  PROMPT:  Title of this product is {}. This from brand {} and has class label is {} 